import mongoose from "mongoose";
import Product from "../models/productModel.js"; // Adjust path if needed

await mongoose.connect("mongodb://localhost:27017/skatchel");

const products = [
  // Shirts
  {
    name: "Classic White Shirt",
    type: "shirt",
    price: 999,
    description: "Cotton formal white shirt",
    imageUrl: "/shirt/shirt1.png",
    stock: 25,
  },
  {
    name: "Denim Blue Shirt",
    type: "shirt",
    price: 1299,
    description: "Stylish blue denim shirt",
    imageUrl: "/shirt/shirt1.png",
    stock: 15,
  },
  {
    name: "Checked Casual Shirt",
    type: "shirt",
    price: 1099,
    description: "Red and black checked shirt",
    imageUrl: "/shirt/shirt1.png",
    stock: 20,
  },
  {
    name: "Black Slim Fit Shirt",
    type: "shirt",
    price: 1499,
    description: "Premium black slim fit",
    imageUrl: "/shirt/shirt1.png",
    stock: 12,
  },
  {
    name: "Linen Beach Shirt",
    type: "shirt",
    price: 1399,
    description: "Light linen shirt for casual wear",
    imageUrl: "/shirt/shirt1.png",
    stock: 18,
  },
  {
    name: "Mandarin Collar Shirt",
    type: "shirt",
    price: 1199,
    description: "Modern mandarin collar design",
    imageUrl: "/shirt/shirt1.png",
    stock: 10,
  },
  {
    name: "Striped Formal Shirt",
    type: "shirt",
    price: 1299,
    description: "Blue striped office shirt",
    imageUrl: "/shirt/shirt1.png",
    stock: 22,
  },
  {
    name: "Flannel Shirt",
    type: "shirt",
    price: 1599,
    description: "Warm and soft flannel shirt",
    imageUrl: "/shirt/shirt1.png",
    stock: 8,
  },
  {
    name: "Half Sleeve Polo",
    type: "shirt",
    price: 899,
    description: "Casual half-sleeve polo shirt",
    imageUrl: "/shirt/shirt1.png",
    stock: 30,
  },
  {
    name: "Printed Casual Shirt",
    type: "shirt",
    price: 1199,
    description: "Printed casual wear shirt",
    imageUrl: "/shirt/shirt1.png",
    stock: 16,
  },

  // Pants
  {
    name: "Slim Fit Jeans",
    type: "pant",
    price: 1799,
    description: "Dark blue slim fit jeans",
    imageUrl: "/pant/pant1.png",
    stock: 20,
  },
  {
    name: "Chino Pants",
    type: "pant",
    price: 1499,
    description: "Beige cotton chinos",
    imageUrl: "/pant/pant1.png",
    stock: 18,
  },
  {
    name: "Black Formal Trousers",
    type: "pant",
    price: 1999,
    description: "Premium black formal pants",
    imageUrl: "/pant/pant1.png",
    stock: 12,
  },
  {
    name: "Cargo Pants",
    type: "pant",
    price: 1599,
    description: "Olive green cargo pants",
    imageUrl: "/pant/pant1.png",
    stock: 15,
  },
  {
    name: "Jogger Pants",
    type: "pant",
    price: 1299,
    description: "Comfortable grey joggers",
    imageUrl: "/pant/pant1.png",
    stock: 25,
  },
  {
    name: "Track Pants",
    type: "pant",
    price: 999,
    description: "Black track pants for workouts",
    imageUrl: "/pant/pant1.png",
    stock: 30,
  },
  {
    name: "Loose Fit Jeans",
    type: "pant",
    price: 1899,
    description: "Relaxed fit light blue jeans",
    imageUrl: "/pant/pant1.png",
    stock: 10,
  },
  {
    name: "Cotton Pajamas",
    type: "pant",
    price: 799,
    description: "Soft cotton night pajamas",
    imageUrl: "/pant/pant1.png",
    stock: 40,
  },
  {
    name: "Pleated Trousers",
    type: "pant",
    price: 1799,
    description: "Classic pleated formal trousers",
    imageUrl: "/pant/pant1.png",
    stock: 9,
  },
  {
    name: "Linen Pants",
    type: "pant",
    price: 1599,
    description: "Breathable linen pants for summer",
    imageUrl: "/pant/pant1.png",
    stock: 14,
  },

  // Bags
  {
    name: "Leather Laptop Bag",
    type: "bag",
    price: 2999,
    description: "Premium leather laptop bag",
    imageUrl: "/bag/bag1.png",
    stock: 10,
  },
  {
    name: "Travel Backpack",
    type: "bag",
    price: 2499,
    description: "Large capacity travel backpack",
    imageUrl: "/bag/bag1.png",
    stock: 15,
  },
  {
    name: "Canvas Tote Bag",
    type: "bag",
    price: 999,
    description: "Eco-friendly canvas tote bag",
    imageUrl: "/bag/bag1.png",
    stock: 25,
  },
  {
    name: "Gym Duffel Bag",
    type: "bag",
    price: 1999,
    description: "Spacious duffel for gym essentials",
    imageUrl: "/bag/bag1.png",
    stock: 20,
  },
  {
    name: "School Backpack",
    type: "bag",
    price: 1499,
    description: "Waterproof school backpack",
    imageUrl: "/bag/bag1.png",
    stock: 30,
  },
  {
    name: "Messenger Bag",
    type: "bag",
    price: 1799,
    description: "Casual messenger bag",
    imageUrl: "/bag/bag1.png",
    stock: 12,
  },
  {
    name: "Camera Bag",
    type: "bag",
    price: 2599,
    description: "Protective bag for camera equipment",
    imageUrl: "/bag/bag1.png",
    stock: 8,
  },
  {
    name: "Trolley Bag",
    type: "bag",
    price: 3999,
    description: "Compact trolley for short trips",
    imageUrl: "/bag/bag1.png",
    stock: 6,
  },
  {
    name: "Handbag for Women",
    type: "bag",
    price: 2299,
    description: "Stylish handbag for daily use",
    imageUrl: "/bag/bag1.png",
    stock: 18,
  },
  {
    name: "Sling Bag",
    type: "bag",
    price: 1199,
    description: "Compact cross-body sling bag",
    imageUrl: "/bag/bag1.png",
    stock: 22,
  },
];

await Product.insertMany(products);
console.log("✅ Data seeded successfully!");

await mongoose.disconnect();
